// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3JYTrhKZyZv3PLv0vTVMu8vg5psVv_9M',
    appId: '1:275631894721:web:af6f2950835af05bf6a440',
    messagingSenderId: '275631894721',
    projectId: 'testgamingsocial-ffe04',
    authDomain: 'testgamingsocial-ffe04.firebaseapp.com',
    storageBucket: 'testgamingsocial-ffe04.firebasestorage.app',
    measurementId: 'G-JHRRGZJB9T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1vyYtYK0rNalAR7uo_yl8Pzmcmx4tOCg',
    appId: '1:275631894721:android:668cc0fb86f4855bf6a440',
    messagingSenderId: '275631894721',
    projectId: 'testgamingsocial-ffe04',
    storageBucket: 'testgamingsocial-ffe04.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0VOcmpbKjGVjOQor6OJiS7Snepi8Nhzo',
    appId: '1:275631894721:ios:c6717740c3d9b894f6a440',
    messagingSenderId: '275631894721',
    projectId: 'testgamingsocial-ffe04',
    storageBucket: 'testgamingsocial-ffe04.firebasestorage.app',
    iosBundleId: 'com.example.gamerSocialHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0VOcmpbKjGVjOQor6OJiS7Snepi8Nhzo',
    appId: '1:275631894721:ios:c6717740c3d9b894f6a440',
    messagingSenderId: '275631894721',
    projectId: 'testgamingsocial-ffe04',
    storageBucket: 'testgamingsocial-ffe04.firebasestorage.app',
    iosBundleId: 'com.example.gamerSocialHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3JYTrhKZyZv3PLv0vTVMu8vg5psVv_9M',
    appId: '1:275631894721:web:47052354d363d047f6a440',
    messagingSenderId: '275631894721',
    projectId: 'testgamingsocial-ffe04',
    authDomain: 'testgamingsocial-ffe04.firebaseapp.com',
    storageBucket: 'testgamingsocial-ffe04.firebasestorage.app',
    measurementId: 'G-J9NQ7XGXY4',
  );
}
